[App.Contracts]
InfraredContractAddress = "0xd0bade66b5ea3fb7efddaa39cadfec5c279b1735" # This is not the correct address.





#### Required for base app ####

[Eth]
# Devnet
EthHTTPURL = "https://devnet.beraswillmakeit.com"
EthWSURL = "ws://devnet.beraswillmakeit.com:8546"

[Server.HTTP]
Port = 8081