#### Contracts that the indexer will be following ####
[App.Contracts]
InfraredContractAddress = "0xA51fc80a8Ec5Cd9181F8917D74D11Bd2c95e4F95"


#### Database configuration ####
[App.DB]
ConnectionURL = "rediss://default:274f2558a6334cbeadb2c2123112564f@eu2-sweeping-tortoise-30656.upstash.io:30656"


#### For cold restarting the service ####
[App.Checkpoint]
LatestBlock=0

#### Required for base app ####
[Eth]
EthHTTPURL = "https://devnet.beraswillmakeit.com"
EthWSURL = "wss://devnet.beraswillmakeit.com:8547"


#### Required for base app ####
[Server.HTTP]
Port = 8080