#### Database configuration ####
[App.DB]
ConnectionURL = "https://api.goldsky.com/api/public/project_clq2g47nauan701ycffzjc71z/subgraphs/infrared-finance/1.0.0/gn"


#### For keeping polling time of jobs ####
[App.Interval]
VaultHarvesterInterval="60s"
ValidatorHarvesterInterval="60s"

#### Signer of the keeper ####
[App.Signer]
PrivateKey = ""

#### VaultHarvester Job Config ####
[App.VaultHarvester]
MinBGT = 200000000000000000
GasLimit = 10e6

#### VaultHarvester Job Config ####
[App.ValidatorHarvester]
MinBera = 1000000000000000000
GasLimit = 10e6

#### Contracts Config ####
[App.ContractsConfig]
InfraredContractAddress = "0xe9faa96e402E18d03CF6C4c0B8eF86793B746BDc"
RewardsPrecompileAddress = ""
DistributionPrecompileAddress = ""


#### Transactor Config ####
[App.Transactor]
Multicall3Address = "0x9d1dB8253105b007DDDE65Ce262f701814B91125"
TxReceiptTimeout = "50s" # ~10 blocks
PendingNonceTimeout = "10s" # ~2 blocks
TxBatchSize = 1
EmtpyQueueDelay = "1s" 
TxBatchTimeout = "5s" # ~1 block
CallTxTimeout = "10s" # ~2 blocks


[ConnectionPool]
EthHTTPURLs = ["https://artio-internal-rpc.berachain.com"]
EthWSURLs = ["wss://artio-internal-rpc.berachain.com:8547"]
DefaultTimeout = "5s"

[Server.HTTP]
Port = 8080

[Log]
Level = "info"
Format = "non-json"