#### Database configuration ####
[App.DB]
ConnectionURL = ""


#### For keeping polling time of jobs ####
[App.Interval]
VaultHarvesterInterval="1s"
ValidatorHarvesterInterval="1s"

#### Signer of the keeper ####
[App.Signer]
PublicKey = ""
PrivateKey = ""

#### VaultHarvester Job Config ####
[App.VaultHarvester]
MinBGT = 1000000000000000000
GasLimit = 10e6

#### VaultHarvester Job Config ####
[App.ValidatorHarvester]
MinBera = 1000000000000000000
GasLimit = 10e6

#### Contracts Config ####
[App.ContractsConfig]
InfraredContractAddress = ""
RewardsPrecompileAddress = ""
DistributionPrecompileAddress = ""

#### Required for base app ####
[Eth]
EthHTTPURL = "https://rpc.berachain-internal.com"
EthWSURL = "wss://ws.berachain-internal.com:8547"


#### Required for base app ####
[Server.HTTP]
Port = 8080