name: pipeline

on:
  pull_request:
  push:
    branches: [main, develop]
    paths:
      - "src/**/*.sol"
      - ".github/workflows/pipeline.yaml"

env:
  FOUNDRY_PROFILE: ci

jobs:
  all:
    strategy:
      fail-fast: true

    runs-on: ubuntu-latest
    steps:
      - name: Clone main repository
        uses: actions/checkout@v4

      - name: Add SSH private keys for submodule repositories
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clone submodules
        run: |
          git submodule set-url lib/contracts-monorepo ssh://git@github.com/berachain/contracts-monorepo
          git submodule update --init --recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge fmt --check
        run: |
          forge fmt --check

      - name: Run Forge tests
        run: |
          FOUNDRY_PROFILE=ci forge test -vvv
        id: test
