name: Slither analysis

# Controls when the action will run. 
on:
  push:
    paths:
    - 'src/**/*.sol'
    - '.github/workflows/slither.yml'

# ensure multiple CI processes are not running analysis on contracts
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
  PULL_NUMBER: ${{ github.event.pull_request.number }}
  RUN_ID: ${{ github.run_id }}

jobs:
  slither:
    runs-on: ubuntu-latest
    steps:
      - name: Clone main repository
        uses: actions/checkout@v4

      - name: Add SSH private keys for submodule repositories
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clone submodules
        run: |
          git submodule set-url lib/contracts-monorepo ssh://git@github.com/berachain/contracts-monorepo
          git submodule update --init --recursive

      # - uses: actions/cache@v3
      #   with:
      #     path: |
      #       forge-cache
      #       out
      #     key: ${{ runner.OS }}-contracts-slither-${{ hashFiles('src/*.sol', 'src/**/*.sol') }}


      # - name: Install Foundry
      #   uses: foundry-rs/foundry-toolchain@v1

      # - name: Compile
      #   run: forge build --build-info

      - name: Run Slither
        uses: crytic/slither-action@v0.4.0
        id: slither
        with:
          slither-args: --checklist
          solc-version: "0.8.26"